'use client';

import { motion } from 'motion/react';
import Link from 'next/link';
import { useBacktestIndex } from '../../hooks/use-backtest';
import { CodeTag } from '../ui/code-tag';

/**
 * Hero-strip on /marketplace: real 90-day backtest numbers for the seeded
 * strategies. Lifted verbatim from the static JSON in /public/backtests,
 * which itself is generated by `scripts/backtest-strategies.ts` against
 * CoinGecko's SUI/USD daily prices.
 */
export function BacktestSummaryStrip() {
  const { data, isLoading } = useBacktestIndex();
  if (isLoading) return null;
  if (!data || data.strategies.length === 0) return null;

  return (
    <motion.section
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="card-flat mb-8 overflow-hidden"
    >
      <div className="flex flex-col gap-2 border-b border-divider p-5 md:flex-row md:items-end md:justify-between">
        <div>
          <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-ink-mute">
            <CodeTag>backtest</CodeTag> · 90-day window ·{' '}
            <span className="text-ink">
              {data.startDate} → {data.endDate}
            </span>
          </p>
          <h2 className="mt-1 font-display text-2xl font-bold tracking-tight md:text-3xl">
            Real returns,{' '}
            <span className="font-serif italic">verifiable inputs</span>.
          </h2>
        </div>
        <p className="max-w-xs text-xs leading-relaxed text-ink-soft">
          Each strategy replayed deterministically against CoinGecko SUI/USD daily prices. The
          same evaluate() function the live runtime uses. 0.25% per-trade fee assumed.
        </p>
      </div>
      <div className="grid grid-cols-3 divide-x divide-divider">
        {data.strategies.map((s) => {
          const slug = s.slug;
          const accent =
            slug === 'conservative-rebalancer'
              ? 'var(--accent-green)'
              : slug === 'balanced-yield'
                ? 'var(--accent-blue)'
                : 'var(--accent-orange)';
          const winning = s.alphaPct >= 0;
          return (
            <Link
              key={slug}
              href={`/marketplace#${slug}`}
              className="group flex flex-col gap-2 p-5 transition-colors hover:bg-paper"
            >
              <div className="flex items-center gap-2">
                <span
                  className="inline-block h-2 w-2 rounded-full"
                  style={{ backgroundColor: accent }}
                />
                <span className="truncate font-display text-[13px] font-semibold leading-tight">
                  {s.name.replace(/^Synapse /, '')}
                </span>
              </div>
              <div className="flex items-baseline gap-2">
                <span
                  className="num-display text-4xl"
                  style={{ color: winning ? 'var(--state-active)' : 'var(--accent-orange)' }}
                >
                  {s.totalReturnPct >= 0 ? '+' : ''}
                  {s.totalReturnPct.toFixed(2)}%
                </span>
              </div>
              <div className="flex flex-wrap gap-x-3 gap-y-1 font-mono text-[10px] uppercase tracking-[0.1em] text-ink-mute">
                <span>
                  α {s.alphaPct >= 0 ? '+' : ''}
                  {s.alphaPct.toFixed(2)}%
                </span>
                <span>DD −{s.maxDrawdownPct.toFixed(1)}%</span>
                <span>Sharpe {s.sharpeAnnualized.toFixed(2)}</span>
                <span>{s.tradesExecuted} trades</span>
              </div>
            </Link>
          );
        })}
      </div>
    </motion.section>
  );
}
