/**
 * Backtest data loader. Reads the static JSON files generated by
 * `scripts/backtest-strategies.ts` from the dashboard `public/` directory.
 * Returns the parsed summary (or null if the file 404s).
 */

// Strategy slugs mirror the IDs in `@synapse-core/vault/strategies`. Kept
// inline so the dashboard bundle doesn't pull in the Node-only runtime deps
// (pino, @mysten/walrus, etc.) that the vault package transitively requires.
const CONSERVATIVE_REBALANCER_ID = 'conservative-rebalancer';
const BALANCED_YIELD_ID = 'balanced-yield';
const AGGRESSIVE_MOMENTUM_ID = 'aggressive-momentum';

export interface BacktestPoint {
  date: string;
  priceUsd: number;
  navUsd: number;
  suiUnits: number;
  usdcUnits: number;
  decision: 'rebalance' | 'noop';
  rationale: string;
}

export interface BacktestSummary {
  strategySlug: string;
  strategyName: string;
  startDate: string;
  endDate: string;
  startNavUsd: number;
  endNavUsd: number;
  totalReturnPct: number;
  benchmarkReturnPct: number;
  alphaPct: number;
  maxDrawdownPct: number;
  volatilityPct: number;
  sharpeAnnualized: number;
  tradesExecuted: number;
  noops: number;
  series: BacktestPoint[];
  generatedAt: string;
}

export interface BacktestIndexEntry {
  slug: string;
  name: string;
  totalReturnPct: number;
  benchmarkReturnPct: number;
  alphaPct: number;
  maxDrawdownPct: number;
  sharpeAnnualized: number;
  tradesExecuted: number;
}

export interface BacktestIndex {
  generatedAt: string;
  startDate: string;
  endDate: string;
  strategies: BacktestIndexEntry[];
}

/**
 * Map an on-chain Strategy name to the canonical backtest slug. The mapping
 * is hardcoded because the on-chain `name` is the only thing the dashboard
 * has before fetching the full Strategy object. Update whenever new
 * strategies are added.
 */
const NAME_TO_SLUG: Record<string, string> = {
  'Synapse Conservative Rebalancer': CONSERVATIVE_REBALANCER_ID,
  'Synapse Balanced Yield': BALANCED_YIELD_ID,
  'Synapse Aggressive Momentum': AGGRESSIVE_MOMENTUM_ID,
};

export function backtestSlugForStrategy(name: string): string | null {
  return NAME_TO_SLUG[name] ?? null;
}

export async function loadBacktestIndex(): Promise<BacktestIndex | null> {
  const res = await fetch('/backtests/index.json', { cache: 'no-store' });
  if (!res.ok) return null;
  return (await res.json()) as BacktestIndex;
}

export async function loadBacktest(slug: string): Promise<BacktestSummary | null> {
  const res = await fetch(`/backtests/${slug}.json`, { cache: 'no-store' });
  if (!res.ok) return null;
  return (await res.json()) as BacktestSummary;
}
